name: [DOCUMENTATION] Documentation Issue
description: Report a problem with documentation
title: "docs: "
labels: ["documentation", "needs-triage"]
assignees: ["shift"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please describe the issue you found.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is affected?
      options:
        - README.md
        - GUIDE.md (API/Server guide)
        - MCP-CONFIGURATION.md
        - CONTRIBUTING.md
        - Code comments/docstrings
        - Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What's wrong with the current documentation?
      placeholder: |
        - Information is unclear
        - Example doesn't work
        - Missing information
        - Outdated content
        - Typo or formatting issue
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where did you find this issue?
      placeholder: |
        - File: README.md
        - Section: Installation
        - Line: 45
        - URL: https://github.com/shift/garnix-insights/...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should this be fixed or improved?
      placeholder: Describe what the documentation should say instead...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Screenshots, related issues, etc...
