name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "feat: "
labels: ["enhancement", "needs-triage"]
assignees: ["shift"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: What would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - CLI tool
        - HTTP server
        - MCP server
        - Garnix API client
        - Documentation
        - Build system
        - Other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - I could work around this by...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      render: text
      placeholder: |
        # CLI example:
        garnix-insights --new-feature value

        # HTTP API example:
        GET /api/new-endpoint

        # MCP example:
        {...}

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references
      placeholder: Links, mockups, related issues...

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am willing to help implement this feature
          required: false
        - label: This feature aligns with the project's goals
          required: true
