title: Garnix Fetcher Docs
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
url: https://shift.github.io
baseurl: /garnix-insights
include:
  - README.md
  - ai-agent-instructions.md
  - MCP-CONFIGURATION.md
  - mcp-usage.md
