name: Publish to Cargo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          
    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: shift
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: Run tests
      run: nix flake check
      
    - name: Build package
      run: nix build .#default
      
    - name: Publish to crates.io
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "🚀 Publishing garnix-insights to crates.io..."
        nix develop -c -- cargo publish --allow-dirty
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Installation
          
          ```bash
          cargo install garnix-insights
          ```
          
          Or with Nix:
          
          ```bash
          nix profile install github:shift/garnix-insights
          ```
        draft: false
        prerelease: false